### ISSUE TITLE
Overlapping Lines

### ISSUE THREAD

**Issue by uksins** [verlox/Veylib#11]
Overlapping Lines:

Print a string to line which is longer than the terminal size, when writing another line, they overlap each other -> super annoying

Steps To Reproduce:
------------------------------

1: core.WriteLine("example") : Longer Than Terminal Width
2: core.WriteLine("example2") -> example is now overlapped here.

Work-Around:
------------------------------

1: core.WriteLine("example") : Longer Than Terminal Width
2: core.Clear() : The Clear Console Command
3: core.WriteLine("example2") : Good

**Comment by verlox** [comment]
yeah its been an issue that ive been ignoring, ill see if i can have a fix out later, its due to some bad math because 9/10 times i work on the library im sleep deprived

**Comment by verlox** [comment]
Fixed in 42afc1aba45fbd68f232f63d8bce9297eb35a6ea, new release [here](https://github.com/verlox/Veylib/releases/tag/V2.4).
